from . import help
from . import start
from . import buyurtma_menu
from . import aksiya_menu
from . import biz_haqimizda
from . import boglanish_menu
from . import sozlamalr_menu
from . import mylocation_menu
from . import echo